# Google Cloud Build Configuration for PsyFi
# Applied Alchemy Labs - ABX-Core v1.3

steps:
  # Build and test
  - name: 'python:3.11'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        pip install --upgrade pip
        pip install -r requirements.txt
        python test_startup.py
    id: 'test'

  # Deploy to App Engine
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['app', 'deploy', 'app.yaml', '--quiet']
    id: 'deploy'

# Timeout for entire build
timeout: '600s'

# Build options
options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'N1_HIGHCPU_8'

# Substitutions
substitutions:
  _SERVICE_NAME: 'psyfi-api'
  _REGION: 'us-central1'
