/** Public package surface — subsystems are independently replaceable. */
export * from './contracts/QualityTier'
export * from './contracts/SceneSnapshot'
export * from './contracts/RenderGraph'
export * from './bridge/SnapshotStore'
export * from './bridge/SnapshotInterpolator'
export * from './bridge/AnalysisPublisher'
export * from './bridge/CameraPipeline'
export * from './AssetPipeline/AssetLoader'
export * from './AssetPipeline/decodeAsset'
export * from './compute'
export * from './ShaderLibrary/registry'
export * from './MaterialSystem'
export * from './Effects'
export * from './Profiling/FrameProfiler'
export * from './PostProcessing/TemporalAccumulate'
export { PsyFiGPUCanvas } from './Renderer/PsyFiGPUCanvas'
export { createWebGPURenderer } from './Renderer/createWebGPURenderer'
